// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebshopAPI.DAL;

namespace WebshopAPI.DAL.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20211107100305_SocketEnumProperty")]
    partial class SocketEnumProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebshopAPI.DAL.Models.CPU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcquisitionPrice")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoreNumber")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("L3Cache")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<int>("SocketType")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AcquisitionPrice = 100,
                            Brand = "INTEL",
                            CoreNumber = 8,
                            ImgURL = "",
                            L3Cache = 24,
                            ProductName = "Test CPU 1",
                            SellPrice = 110,
                            SocketType = 27,
                            Speed = 3700
                        },
                        new
                        {
                            ID = 2,
                            AcquisitionPrice = 120,
                            Brand = "AMD",
                            CoreNumber = 12,
                            ImgURL = "",
                            L3Cache = 32,
                            ProductName = "Test CPU 2",
                            SellPrice = 140,
                            SocketType = 11,
                            Speed = 3900
                        });
                });

            modelBuilder.Entity("WebshopAPI.DAL.Models.Motherboard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcquisitionPrice")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CPUSocketType")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxMemorySize")
                        .HasColumnType("int");

                    b.Property<string>("MemorySocketType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfMemorySockets")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<string>("SizeStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usb3Amount")
                        .HasColumnType("int");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AcquisitionPrice = 80,
                            Brand = "ASUS",
                            CPUSocketType = 11,
                            ImgURL = "",
                            MaxMemorySize = 128,
                            MemorySocketType = "DDR4",
                            NumberOfMemorySockets = 4,
                            ProductName = "Test Motherboard 1",
                            SellPrice = 95,
                            SizeStandard = "ATX",
                            Usb3Amount = 8,
                            Wifi = true
                        },
                        new
                        {
                            ID = 2,
                            AcquisitionPrice = 110,
                            Brand = "MSI",
                            CPUSocketType = 27,
                            ImgURL = "",
                            MaxMemorySize = 128,
                            MemorySocketType = "DDR5",
                            NumberOfMemorySockets = 4,
                            ProductName = "Test Motherboard 2",
                            SellPrice = 125,
                            SizeStandard = "EATX",
                            Usb3Amount = 6,
                            Wifi = true
                        });
                });

            modelBuilder.Entity("WebshopAPI.DAL.Models.RAM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcquisitionPrice")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Delay")
                        .HasColumnType("int");

                    b.Property<int>("Gb")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SellPrice")
                        .HasColumnType("int");

                    b.Property<string>("SocketType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("RAMs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AcquisitionPrice = 30,
                            Brand = "G.SKILL",
                            Delay = 8,
                            Gb = 32,
                            ImgURL = "",
                            ProductName = "Test RAM 1",
                            SellPrice = 35,
                            SocketType = "DDR4",
                            Speed = 4200
                        },
                        new
                        {
                            ID = 2,
                            AcquisitionPrice = 80,
                            Brand = "KINGSTON",
                            Delay = 12,
                            Gb = 64,
                            ImgURL = "",
                            ProductName = "Test RAM 2",
                            SellPrice = 99,
                            SocketType = "DDR5",
                            Speed = 6700
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
